name: Daily Log Commit

on:
  schedule:
    - cron: '0 15 * * *'  # 22h giờ Việt Nam (UTC+7)
  workflow_dispatch:

jobs:
  daily-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create daily log
        run: |
          mkdir -p logs
          NOW=$(date '+%Y-%m-%d')
          echo "Log ngày $NOW: Tôi đang giữ tài khoản này active." > logs/$NOW-log.txt

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add logs/
          git commit -m "📝 Daily log for $(date '+%Y-%m-%d')" || echo "Không có gì để commit"
          git push
